basePath: /
definitions:
  account.ChangePasswordRequest:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    type: object
  account.ChangePasswordResponse:
    properties:
      message:
        type: string
    type: object
  account.ForgotPasswordRequest:
    properties:
      email:
        type: string
    type: object
  account.ForgotPasswordResponse:
    properties:
      message:
        type: string
    type: object
  account.GetProfileResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
  account.LoginAccountRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  account.LoginAccountResponse:
    properties:
      token:
        type: string
    type: object
  account.RegisterAccountRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  account.RegisterAccountResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      token:
        type: string
    type: object
  account.ResetPasswordRequest:
    properties:
      password:
        type: string
      token:
        type: string
    type: object
  account.ResetPasswordResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API for the spsyncpro platform.
  title: spsyncpro API
  version: "1.0"
paths:
  /api/v1/account/change-password:
    post:
      consumes:
      - application/json
      description: Change Password
      parameters:
      - description: Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.ChangePasswordResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Change Password
      tags:
      - account
  /api/v1/account/forgot-password:
    post:
      consumes:
      - application/json
      description: Forgot Password
      parameters:
      - description: Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.ForgotPasswordResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Forgot Password
      tags:
      - account
  /api/v1/account/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.LoginAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.LoginAccountResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login a user
      tags:
      - account
  /api/v1/account/logout:
    post:
      consumes:
      - application/json
      description: Logout a user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Logout a user
      tags:
      - account
  /api/v1/account/profile:
    get:
      consumes:
      - application/json
      description: Get Profile of the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.GetProfileResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get Profile
      tags:
      - account
  /api/v1/account/register:
    post:
      consumes:
      - application/json
      description: Register a new account
      parameters:
      - description: Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.RegisterAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.RegisterAccountResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new account
      tags:
      - account
  /api/v1/account/reset-password:
    post:
      consumes:
      - application/json
      description: Reset Password
      parameters:
      - description: Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.ResetPasswordResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Reset Password
      tags:
      - account
schemes:
- http
swagger: "2.0"
